# Generated by Django 4.1 on 2022-08-04 02:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "date",
                    models.DateField(
                        default=datetime.datetime(2022, 8, 4, 2, 41, 28, 103354),
                        verbose_name="Expense Date",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="Expense Cost"
                    ),
                ),
                (
                    "is_validated",
                    models.BooleanField(default=False, verbose_name="Is validated?"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ExpenseGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active?"),
                ),
                (
                    "members",
                    models.ManyToManyField(
                        related_name="expenses_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallet",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expenses_groups",
                    models.ManyToManyField(
                        related_name="items_tags", to="core.expensegroup"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Regarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "start_date",
                    models.DateField(
                        default=datetime.datetime(2022, 8, 4, 2, 41, 28, 101046),
                        verbose_name="Start Date",
                    ),
                ),
                ("end_date", models.DateField(null=True, verbose_name="End Date")),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="Is closed?"),
                ),
                (
                    "balance_json",
                    models.JSONField(default=dict, verbose_name="Balance Data"),
                ),
                (
                    "expense_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="regardings",
                        to="core.expensegroup",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.TextField(
                        choices=[
                            ("DEBIT", "CARTÃO DE DÉBITO"),
                            ("CREDIT", "CARTÃO DE CRÉDITO"),
                            ("CASH", "DINHEIRO"),
                        ],
                        verbose_name="Payment Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "limit",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="Payment Limit Value",
                    ),
                ),
                (
                    "compensation_date",
                    models.DateField(
                        default=datetime.datetime(2022, 8, 4, 2, 41, 28, 102226),
                        verbose_name="Payment Due Date",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Payment Method is active?"
                    ),
                ),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_methods",
                        to="core.wallet",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="Payment Value"
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("VALIDATION", "EM VALIDAÇÃO"),
                            ("AWAITING", "AGUARDANDO PAGAMENTO"),
                            ("PAID", "PAGO"),
                            ("OVERDUE", "VENCIDO"),
                        ],
                        default="VALIDATION",
                        max_length=128,
                        verbose_name="Payment Status",
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.expense",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="paid_expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="core.paymentmethod",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=4, max_digits=14, verbose_name="Price"
                    ),
                ),
                (
                    "consumers",
                    models.ManyToManyField(
                        related_name="items_purchased", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "expense",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="core.expense",
                    ),
                ),
                (
                    "tags",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="core.tag",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="expense",
            name="regarding",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="core.regarding",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="validated_by",
            field=models.ManyToManyField(
                related_name="validated_expenses", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
