# Generated by Django 4.1 on 2022-08-06 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0003_alter_expense_date_and_more")]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="name",
            field=models.CharField(
                default="Outros", max_length=128, verbose_name="Tag"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(
                default=datetime.date(2022, 8, 6), verbose_name="Expense Date"
            ),
        ),
        migrations.AlterField(
            model_name="paymentmethod",
            name="compensation_date",
            field=models.DateField(
                default=datetime.date(2022, 8, 6), verbose_name="Payment Due Date"
            ),
        ),
        migrations.AlterField(
            model_name="regarding",
            name="start_date",
            field=models.DateField(
                default=datetime.date(2022, 8, 6), verbose_name="Start Date"
            ),
        ),
    ]
