# Generated by Django 4.1 on 2022-08-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0004_tag_name_alter_expense_date_and_more")]

    operations = [
        migrations.RemoveField(model_name="paymentmethod", name="compensation_date"),
        migrations.AddField(
            model_name="paymentmethod",
            name="compensation_day",
            field=models.IntegerField(
                null=True, verbose_name="Payment Compensation Day"
            ),
        ),
    ]
