# Generated by Django 4.1 on 2022-08-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0005_remove_paymentmethod_compensation_date_and_more")]

    operations = [
        migrations.AlterField(
            model_name="paymentmethod",
            name="compensation_day",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Payment Compensation Day"
            ),
        )
    ]
