# Generated by Django 4.1 on 2022-08-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0006_alter_paymentmethod_compensation_day")]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="core.tag",
            ),
        )
    ]
