# Generated by Django 4.1 on 2023-03-16 23:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0007_alter_item_tags")]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 3, 16), verbose_name="Expense Date"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="tags",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.tag",
            ),
        ),
        migrations.AlterField(
            model_name="regarding",
            name="start_date",
            field=models.DateField(
                default=datetime.date(2023, 3, 16), verbose_name="Start Date"
            ),
        ),
    ]
