# Generated by Django 4.1 on 2023-03-16 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0008_alter_expense_date_alter_item_tags_and_more")]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.expense",
            ),
        )
    ]
