# Generated by Django 4.1 on 2023-03-18 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0012_alter_expense_validated_by")]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 3, 18), verbose_name="Expense Date"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="core.expense",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="expense",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="core.expense",
            ),
        ),
        migrations.AlterField(
            model_name="regarding",
            name="start_date",
            field=models.DateField(
                default=datetime.date(2023, 3, 18), verbose_name="Start Date"
            ),
        ),
    ]
