# Generated by Django 4.1 on 2023-03-25 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_expense_date_alter_item_expense_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 25), verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='limit',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True, verbose_name='Payment Limit Value'),
        ),
        migrations.AlterField(
            model_name='regarding',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 3, 25), verbose_name='Start Date'),
        ),
    ]
