# Generated by Django 4.1 on 2023-03-25 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_address_number_user_city_user_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='validated_by',
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validated_at', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='core.expense')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_validations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='Notification Title')),
                ('body', models.TextField(verbose_name='Notification Body')),
                ('payload', models.JSONField(null=True, verbose_name='Notification Payload')),
                ('was_sent', models.BooleanField(default=False, verbose_name='Notification sent?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
