# Generated by Django 4.1 on 2023-03-25 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_expense_validated_by_validation_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='validated_by',
            field=models.ManyToManyField(blank=True, null=True, through='core.Validation', to=settings.AUTH_USER_MODEL),
        ),
    ]
