# Generated by Django 4.1 on 2023-03-25 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_expense_validated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='validation',
            name='validated_at',
            field=models.DateField(blank=True, null=True, verbose_name='Validation Date'),
        ),
    ]
