# Generated by Django 4.1 on 2023-03-26 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_notification_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active?'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 26), verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='regarding',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 3, 26), verbose_name='Start Date'),
        ),
    ]
