# Generated by Django 4.1 on 2023-03-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_validation_is_active_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Notification Payload'),
        ),
    ]
