# Generated by Django 4.1 on 2023-03-26 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_notification_payload'),
    ]

    operations = [
        migrations.AddField(
            model_name='validation',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Note'),
        ),
    ]
