# Generated by Django 4.1 on 2023-03-27 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_validation_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensegroup',
            name='members',
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 27), verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='regarding',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 3, 27), verbose_name='Start Date'),
        ),
    ]
