# Generated by Django 4.1 on 2023-03-27 20:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_expensegroup_members_alter_expense_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateField(auto_now_add=True, verbose_name='Join date')),
                ('average_weight', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True, verbose_name='Weight for shared total')),
            ],
        ),
        migrations.AddField(
            model_name='expensegroup',
            name='members',
            field=models.ManyToManyField(related_name='expenses_groups', through='core.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expensegroup'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
