# Generated by Django 4.1 on 2023-03-28 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_membership_expensegroup_members_membership_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_validated',
        ),
        migrations.AddField(
            model_name='expense',
            name='validation_status',
            field=models.CharField(choices=[('VALIDATION', 'PENDENTE'), ('VALIDATED', 'VALIDADA'), ('REJECTED', 'REJEITADA')], default='VALIDATION', max_length=128, verbose_name='Validation Status'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 28), verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='average_weight',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=7, null=True, verbose_name='Weight for shared total'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.expense'),
        ),
        migrations.AlterField(
            model_name='regarding',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 3, 28), verbose_name='Start Date'),
        ),
    ]
