# Generated by Django 4.1 on 2023-03-30 20:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_expense_is_validated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 3, 30), verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='regarding',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 3, 30), verbose_name='Start Date'),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('CREATE', 'CRIOU'), ('UPDATE', 'EDITOU'), ('DELETE', 'DELETOU')], default='CREATE', max_length=128, verbose_name='Action type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('expense_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_log', to='core.expensegroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
