# Generated by Django 4.1 on 2023-08-03 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_expense_date_alter_regarding_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='level',
            field=models.TextField(choices=[('ADMIN', 'ADMINISTRADOR'), ('EDITOR', 'EDITOR'), ('READER', 'LEITOR')], default='READER', verbose_name='Level'),
        ),
    ]
