# Generated by Django 4.1 on 2023-08-04 20:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_membership_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 4), verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='regarding',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 8, 4), verbose_name='Start Date'),
        ),
        migrations.CreateModel(
            name='GroupInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('AWAITING', 'PENDENTE'), ('ACCEPTED', 'ACEITO'), ('REJECTED', 'REJEITADO')], default='AWAITING', max_length=128, verbose_name='Status')),
                ('expense_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.expensegroup')),
                ('send_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
