# Generated by Django 4.1 on 2023-08-04 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_expense_date_alter_regarding_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupinvitation',
            name='send_by',
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='invited',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupinvitation',
            name='sent_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations_sent', to=settings.AUTH_USER_MODEL),
        ),
    ]
