# Generated by Django 4.1 on 2023-08-05 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_remove_groupinvitation_send_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 5), verbose_name='Expense Date'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='level',
            field=models.TextField(choices=[('ADMIN', 'ADMINISTRADOR'), ('EDITOR', 'EDITOR'), ('READER', 'LEITOR')], default='EDITOR', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='regarding',
            name='start_date',
            field=models.DateField(default=datetime.date(2023, 8, 5), verbose_name='Start Date'),
        ),
    ]
