# Generated by Django 4.1 on 2023-08-08 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_alter_expense_date_alter_membership_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("VALIDATION", "EM VALIDAÇÃO"),
                    ("AWAITING", "AGUARDANDO PAGAMENTO"),
                    ("PAID", "PAGO"),
                    ("OVERDUE", "VENCIDO"),
                ],
                default="VALIDATION",
                max_length=128,
                verbose_name="Payment Status",
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 8, 8), verbose_name="Expense Date"
            ),
        ),
        migrations.AlterField(
            model_name="regarding",
            name="start_date",
            field=models.DateField(
                default=datetime.date(2023, 8, 8), verbose_name="Start Date"
            ),
        ),
    ]
