# Generated by Django 4.1 on 2023-10-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_alter_expense_date_alter_regarding_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="gallery",
            field=models.JSONField(blank=True, null=True, verbose_name="Gallery"),
        ),
    ]
