# Generated by Django 4.1 on 2023-10-29 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_expense_gallery"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensegroup",
            name="drive_id",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Hash ID"
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(
                default=datetime.date(2023, 10, 29), verbose_name="Expense Date"
            ),
        ),
        migrations.AlterField(
            model_name="regarding",
            name="start_date",
            field=models.DateField(
                default=datetime.date(2023, 10, 29), verbose_name="Start Date"
            ),
        ),
    ]
